# Generated by Django 5.0.6 on 2024-07-13 11:04

import card_manager.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('series', models.CharField(default=card_manager.utils.generate_series, help_text='Series of the card', max_length=2)),
                ('id_number', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular card across the whole system', primary_key=True, serialize=False)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField(help_text='The amount of bonus points granted to a customer')),
                ('status', models.CharField(blank=True, choices=[('n', 'Not activated'), ('a', 'Activated'), ('e', 'Expired')], default='n', help_text='Status of the card', max_length=1)),
            ],
        ),
    ]
