# Generated by Django 5.0.6 on 2024-07-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0002_alter_card_id_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['series', 'id_number']},
        ),
        migrations.AlterField(
            model_name='card',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount of bonus points granted to a customer', max_digits=10),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='The amount of bonus points granted to a customer', max_digits=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='card_manager.card')),
            ],
        ),
    ]
