# Generated by Django 5.0.6 on 2024-07-20 15:13

import card_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0003_alter_card_options_alter_card_amount_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expires',
            field=models.DateTimeField(default=card_manager.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not activated'), ('a', 'Activated'), ('e', 'Expired')], default='a', help_text='Status of the card', max_length=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
